#!/bin/bash

##
#
# Various Locations and Config options
#
##
WALLPAPER_DIR=/home/jp/Pictures/Wallpapers
PALETTE_DIR=/home/jp/Pictures/Wallpapers/Palettes
TERMITE_CONFIG=/home/jp/.config/termite/config
FIREFOX_THEME=/home/jp/.mozilla/extensions/dynamicTheme/firefox_theme.json
